version: '3.7'
secrets:
  dev-auth-idp.crt:
    file: dev-auth-idp.crt
  dev-auth-idp.key:
    file: dev-auth-idp.key
  dev-gateway-ssl.crt:
    file: dev-gateway-ssl.crt
  dev-gateway-ssl.key:
    file: dev-gateway-ssl.key
services:
  tkdo-dev-auth-idp:
    build: ./dev-auth-idp
    volumes:
      - tkdo-dev-auth-idp-logs:/var/log
    secrets:
      - source: dev-auth-idp.crt
        target: /var/simplesamlphp/cert/server.crt
      - source: dev-auth-idp.key
        target: /var/simplesamlphp/cert/server.pem
  tkdo-dev-gateway:
    build: ./dev-gateway
    ports:
      - "443:443"
    volumes:
      - tkdo-dev-gateway-logs:/var/log
    secrets:
      - source: dev-gateway-ssl.crt
        target: /usr/local/apache2/conf/server.crt
      - source: dev-gateway-ssl.key
        target: /usr/local/apache2/conf/server.key
volumes:
  tkdo-dev-auth-idp-logs: {}
  tkdo-dev-gateway-logs: {}
