version: '3.7'
services:

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    networks:
      - back
      - dbtools
    secrets:
      - mysql_database
      - mysql_password
      - mysql_root_password
      - mysql_user
    volumes:
      - database-data:/var/lib/mysql

  db-tools:
    depends_on:
      - database
    image: tkdo/db-tools
    environment:
      TKDO_CONNECTION_TYPE: mysql
      TKDO_CONNECTION_HOST: database
      TKDO_CONNECTION_USERNAME_FILE: /run/secrets/mysql_user
      TKDO_CONNECTION_PASSWORD_FILE: /run/secrets/mysql_password
      TKDO_CONNECTION_DATABASE_FILE: /run/secrets/mysql_database
      TKDO_JWT_PUBLIC_KEY_FILE: /run/secrets/auth-sp.key.pub
    networks:
      - dbtools
    secrets:
      - mysql_database
      - mysql_password
      - mysql_user

  tkdo-auth-sp:
    depends_on:
      - tkdo-auth-idp
      - database
    environment:
      TKDO_JWT_PRIVATE_KEY_FILE: /run/secrets/auth-sp.key
      TKDO_SAML_CALLBACK_URL: https://localhost/auth-sp/acs
      TKDO_SAML_ENTRY_POINT: https://localhost/auth-idp/saml2/idp/SSOService.php
      TKDO_SAML_IDP_CERT_FILE: /run/secrets/cert.crt
      TKDO_SAML_ISSUER: https://localhost/auth-sp
      TKDO_SAML_SP_CERT_FILE: /run/secrets/cert.crt
      TKDO_SAML_SP_PRIVATE_KEY_FILE: /run/secrets/cert.pem
      TKDO_TYPEORM_CONNECTION: mysql
      TKDO_TYPEORM_DATABASE: tkdo
      TKDO_TYPEORM_HOST: database
      TKDO_TYPEORM_USERNAME: tkdo
      TKDO_TYPEORM_PASSWORD: qrCtmOHjhDQakmk7
      TKDO_PORT: 3000
    image: tkdo-auth-sp
    secrets:
      - auth-sp.key
      - cert.crt
      - cert.pem

  tkdo-auth-idp:
    image: tkdo-auth-idp
    secrets:
      - source: cert.crt
        target: /var/simplesamlphp/cert/auth-sp.crt
      - source: cert.crt
        target: /var/simplesamlphp/cert/server.crt
      - source: cert.pem
        target: /var/simplesamlphp/cert/server.pem

  tkdo-back:
    depends_on:
      - database
    environment:
      TKDO_TYPEORM_CONNECTION: mysql
      TKDO_TYPEORM_DATABASE: tkdo
      TKDO_TYPEORM_HOST: database
      TKDO_TYPEORM_USERNAME: tkdo
      TKDO_TYPEORM_PASSWORD: qrCtmOHjhDQakmk7
      TKDO_JWT_PUBLIC_KEY_FILE: /run/secrets/auth-sp.key.pub
    image: tkdo-back
    secrets:
      - auth-sp.key.pub

  tkdo-front:
    depends_on:
      - tkdo-auth-sp
      - tkdo-back
    image: tkdo-front

  tkdo-gateway:
    depends_on:
      - tkdo-auth-idp
      - tkdo-auth-sp
      - tkdo-back
      - tkdo-front
    image: tkdo-gateway
    ports:
      - "443:443"
    secrets:
      - source: cert.crt
        target: /usr/local/apache2/conf/server.crt
      - source: cert.pem
        target: /usr/local/apache2/conf/server.key
  
networks:
  front:
  back:
  dbtools:

secrets:
  auth-sp.key:
    file: secrets/auth-sp.key
  auth-sp.key.pub:
    file: secrets/auth-sp.key.pub
  cert.crt:
    file: secrets/cert.crt
  cert.pem:
    file: secrets/cert.pem
  mysql_database:
    file: secrets/mysql_database
  mysql_password:
    file: secrets/mysql_password
  mysql_root_password:
    file: secrets/mysql_root_password
  mysql_user:
    file: secrets/mysql_user

volumes:
  database-data: {}
