version: '3.7'
secrets:
  auth-sp-jwt.key:
    file: auth-sp-jwt.key
  auth-sp-jwt.key.pub:
    file: auth-sp-jwt.key.pub
  auth-sp-saml.key:
    file: auth-sp-saml.key
  auth-sp-saml.crt:
    file: auth-sp-saml.crt
services:
  tkdo-auth-sp:
    build:
      args:
        - NPM_CONFIG_REGISTRY
      context: ./auth-sp
      network: host
    secrets:
      - auth-sp-jwt.key
      - auth-sp-saml.crt
      - auth-sp-saml.key
  tkdo-front:
    build: ./front
    secrets:
      - auth-sp-jwt.key.pub
    volumes:
      - tkdo-front-logs:/var/log
volumes:
  tkdo-front-logs: {}
