version: '3.7'
secrets:
  auth-idp-cert.crt:
    file: auth-idp-cert.crt
  auth-idp-cert.key:
    file: auth-idp-cert.key
  auth-sp-cert.crt:
    file: auth-sp-cert.crt
  auth-sp-cert.key:
    file: auth-sp-cert.key
  auth-sp-sign.key:
    file: auth-sp-sign.key
  auth-sp-sign.key.pub:
    file: auth-sp-sign.key.pub
  gateway-cert.crt:
    file: gateway-cert.crt
  gateway-cert.key:
    file: gateway-cert.key
services:
  tkdo-auth-sp:
    build:
      args:
        - NPM_CONFIG_REGISTRY
      context: ./auth-sp
      network: host
    environment:
      - NODE_ENV=production
      - TKDO_JWT_PRIVATE_KEY_FILE=/run/secrets/auth-sp-sign.key
      - TKDO_SAML_CALLBACK_URL=https://localhost/auth-sp/acs
      - TKDO_SAML_ENTRY_POINT=https://localhost/auth-idp/saml2/idp/SSOService.php
      - TKDO_SAML_IDP_CERT_FILE=/run/secrets/auth-idp-cert.crt
      - TKDO_SAML_ISSUER=https://localhost/auth-sp
      - TKDO_SAML_SP_CERT_FILE=/run/secrets/auth-sp-cert.crt
      - TKDO_SAML_SP_PRIVATE_KEY_FILE=/run/secrets/auth-sp-cert.key
      - TKDO_PORT=3000
    secrets:
      - auth-idp-cert.crt
      - auth-sp-cert.crt
      - auth-sp-cert.key
      - auth-sp-sign.key
  tkdo-auth-idp:
    build: ./auth-idp
    volumes:
      - tkdo-auth-idp-logs:/var/log
    secrets:
      - source: auth-idp-cert.crt
        target: /var/simplesamlphp/cert/server.crt
      - source: auth-idp-cert.key
        target: /var/simplesamlphp/cert/server.pem
  tkdo-back:
    build:
      args:
        - NPM_CONFIG_REGISTRY
      context: ./back
      network: host
    environment:
      - NODE_ENV=production
      - TKDO_JWT_PUBLIC_KEY_FILE=/run/secrets/auth-sp-sign.key.pub
    secrets:
      - auth-sp-sign.key.pub
  tkdo-front:
    build: ./front
    secrets:
      - auth-sp-sign.key.pub
    volumes:
      - tkdo-front-logs:/var/log
  tkdo-gateway:
    build: ./gateway
    ports:
      - "443:443"
    volumes:
      - tkdo-gateway-logs:/var/log
    secrets:
      - source: gateway-cert.crt
        target: /usr/local/apache2/conf/server.crt
      - source: gateway-cert.key
        target: /usr/local/apache2/conf/server.key
volumes:
  tkdo-auth-idp-logs: {}
  tkdo-front-logs: {}
  tkdo-gateway-logs: {}
