version: '3.8'

services:
    front:
        build: ./docker/build-front
        depends_on:
            - angular
            - angular-watch
            - cli
            - slim
        ports:
            - 8080:80
