version: '3.8'

volumes:
    mysql-data:

services:
    slim:
        build: ./docker/slim
        working_dir: /var/www
        user: "${SLIM_UID}:${SLIM_GUID}"
        command: php -S 0.0.0.0:8080 -t public
        environment:
            TKDO_ENV: docker
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
    mysql:
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        image: mysql:5.6
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - mysql-data:/var/lib/mysql